min_acl: private
swift_build_tool: xcodebuild
xcodebuild_arguments:
- -project
- Crwx.xcodeproj
- -scheme
- Crwx
theme: fullwidth
author: Matthew Goacher
author_url: http://www.saltily.com/
title: Crwx
github_url: https://github.com/saltily/Crwx.git
custom_categories:
- name: Crwx
  children:
  - Crwx
